<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="OpenCvSharp4" Version="4.10.0.20241108" />
    <PackageReference Include="OpenCvSharp4.runtime.win" Version="4.10.0.20241108" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\MechMaker.Engine\MechMaker.Engine.csproj" />
    <ProjectReference Include="..\MechMaker.Core\MechMaker.Core.csproj" />
  </ItemGroup>

</Project>
