<Project Sdk="Microsoft.NET.Sdk">

  <ItemGroup>
    <ProjectReference Include="..\MechMaker.Core\MechMaker.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Evergine.Bindings.MuJoCo" Version="2026.8.11.2" />
  </ItemGroup>

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <AllowUnsafeBlocks>true</AllowUnsafeBlocks>
  </PropertyGroup>

</Project>
